# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import p2p_pb2 as p2p__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in p2p_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class P2PNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveVectors = channel.unary_unary(
                '/p2p.P2PNode/ReceiveVectors',
                request_serializer=p2p__pb2.AddVectorsRequest.SerializeToString,
                response_deserializer=p2p__pb2.Empty.FromString,
                _registered_method=True)
        self.QueryPeer = channel.unary_unary(
                '/p2p.P2PNode/QueryPeer',
                request_serializer=p2p__pb2.QueryRequest.SerializeToString,
                response_deserializer=p2p__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.RegisterPeers = channel.unary_unary(
                '/p2p.P2PNode/RegisterPeers',
                request_serializer=p2p__pb2.RegisterPeersRequest.SerializeToString,
                response_deserializer=p2p__pb2.Empty.FromString,
                _registered_method=True)
        self.SetClusters = channel.unary_unary(
                '/p2p.P2PNode/SetClusters',
                request_serializer=p2p__pb2.SetClustersRequest.SerializeToString,
                response_deserializer=p2p__pb2.Empty.FromString,
                _registered_method=True)


class P2PNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveVectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPeer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetClusters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_P2PNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveVectors,
                    request_deserializer=p2p__pb2.AddVectorsRequest.FromString,
                    response_serializer=p2p__pb2.Empty.SerializeToString,
            ),
            'QueryPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPeer,
                    request_deserializer=p2p__pb2.QueryRequest.FromString,
                    response_serializer=p2p__pb2.QueryResponse.SerializeToString,
            ),
            'RegisterPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPeers,
                    request_deserializer=p2p__pb2.RegisterPeersRequest.FromString,
                    response_serializer=p2p__pb2.Empty.SerializeToString,
            ),
            'SetClusters': grpc.unary_unary_rpc_method_handler(
                    servicer.SetClusters,
                    request_deserializer=p2p__pb2.SetClustersRequest.FromString,
                    response_serializer=p2p__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'p2p.P2PNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('p2p.P2PNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class P2PNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.P2PNode/ReceiveVectors',
            p2p__pb2.AddVectorsRequest.SerializeToString,
            p2p__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.P2PNode/QueryPeer',
            p2p__pb2.QueryRequest.SerializeToString,
            p2p__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.P2PNode/RegisterPeers',
            p2p__pb2.RegisterPeersRequest.SerializeToString,
            p2p__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetClusters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.P2PNode/SetClusters',
            p2p__pb2.SetClustersRequest.SerializeToString,
            p2p__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
