// Configuration file for Vector Query Client
// This file is auto-generated by startup.py with the correct server URL.
// If running manually, you can set window.SERVER_URL here or use the Settings modal.

// Example:
// window.SERVER_URL = 'http://localhost:8001';
