# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from protos import p2p_pb2 as protos_dot_p2p__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in protos/p2p_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class P2PNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetId = channel.unary_unary(
            "/p2p.P2PNode/GetId",
            request_serializer=protos_dot_p2p__pb2.Empty.SerializeToString,
            response_deserializer=protos_dot_p2p__pb2.IdResponse.FromString,
            _registered_method=True,
        )
        self.Similarity = channel.unary_unary(
            "/p2p.P2PNode/Similarity",
            request_serializer=protos_dot_p2p__pb2.VectorRequest.SerializeToString,
            response_deserializer=protos_dot_p2p__pb2.SimilarityResponse.FromString,
            _registered_method=True,
        )
        self.Receive = channel.unary_unary(
            "/p2p.P2PNode/Receive",
            request_serializer=protos_dot_p2p__pb2.ReceiveRequest.SerializeToString,
            response_deserializer=protos_dot_p2p__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.IAmCoord = channel.unary_unary(
            "/p2p.P2PNode/IAmCoord",
            request_serializer=protos_dot_p2p__pb2.Empty.SerializeToString,
            response_deserializer=protos_dot_p2p__pb2.BoolResponse.FromString,
            _registered_method=True,
        )
        self.SetClusters = channel.unary_unary(
            "/p2p.P2PNode/SetClusters",
            request_serializer=protos_dot_p2p__pb2.SetClustersRequest.SerializeToString,
            response_deserializer=protos_dot_p2p__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.SearchVectorsLocal = channel.unary_unary(
            "/p2p.P2PNode/SearchVectorsLocal",
            request_serializer=protos_dot_p2p__pb2.SearchVectorsContext.SerializeToString,
            response_deserializer=protos_dot_p2p__pb2.SearchResponse.FromString,
            _registered_method=True,
        )
        self.Query = channel.unary_unary(
            "/p2p.P2PNode/Query",
            request_serializer=protos_dot_p2p__pb2.QueryRequest.SerializeToString,
            response_deserializer=protos_dot_p2p__pb2.QueryResponse.FromString,
            _registered_method=True,
        )
        self.GetVectorDigest = channel.unary_unary(
            "/p2p.P2PNode/GetVectorDigest",
            request_serializer=protos_dot_p2p__pb2.Empty.SerializeToString,
            response_deserializer=protos_dot_p2p__pb2.DigestResponse.FromString,
            _registered_method=True,
        )
        self.GetVectorsByIds = channel.unary_unary(
            "/p2p.P2PNode/GetVectorsByIds",
            request_serializer=protos_dot_p2p__pb2.IdList.SerializeToString,
            response_deserializer=protos_dot_p2p__pb2.VectorList.FromString,
            _registered_method=True,
        )
        self.GetPartitionCoordinatorId = channel.unary_unary(
            "/p2p.P2PNode/GetPartitionCoordinatorId",
            request_serializer=protos_dot_p2p__pb2.Empty.SerializeToString,
            response_deserializer=protos_dot_p2p__pb2.IdResponse.FromString,
            _registered_method=True,
        )
        self.RespondToPing = channel.unary_unary(
            "/p2p.P2PNode/RespondToPing",
            request_serializer=protos_dot_p2p__pb2.Empty.SerializeToString,
            response_deserializer=protos_dot_p2p__pb2.BoolResponse.FromString,
            _registered_method=True,
        )


class P2PNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Similarity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Receive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def IAmCoord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetClusters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SearchVectorsLocal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetVectorDigest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetVectorsByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPartitionCoordinatorId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RespondToPing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_P2PNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetId": grpc.unary_unary_rpc_method_handler(
            servicer.GetId,
            request_deserializer=protos_dot_p2p__pb2.Empty.FromString,
            response_serializer=protos_dot_p2p__pb2.IdResponse.SerializeToString,
        ),
        "Similarity": grpc.unary_unary_rpc_method_handler(
            servicer.Similarity,
            request_deserializer=protos_dot_p2p__pb2.VectorRequest.FromString,
            response_serializer=protos_dot_p2p__pb2.SimilarityResponse.SerializeToString,
        ),
        "Receive": grpc.unary_unary_rpc_method_handler(
            servicer.Receive,
            request_deserializer=protos_dot_p2p__pb2.ReceiveRequest.FromString,
            response_serializer=protos_dot_p2p__pb2.Empty.SerializeToString,
        ),
        "IAmCoord": grpc.unary_unary_rpc_method_handler(
            servicer.IAmCoord,
            request_deserializer=protos_dot_p2p__pb2.Empty.FromString,
            response_serializer=protos_dot_p2p__pb2.BoolResponse.SerializeToString,
        ),
        "SetClusters": grpc.unary_unary_rpc_method_handler(
            servicer.SetClusters,
            request_deserializer=protos_dot_p2p__pb2.SetClustersRequest.FromString,
            response_serializer=protos_dot_p2p__pb2.Empty.SerializeToString,
        ),
        "SearchVectorsLocal": grpc.unary_unary_rpc_method_handler(
            servicer.SearchVectorsLocal,
            request_deserializer=protos_dot_p2p__pb2.SearchVectorsContext.FromString,
            response_serializer=protos_dot_p2p__pb2.SearchResponse.SerializeToString,
        ),
        "Query": grpc.unary_unary_rpc_method_handler(
            servicer.Query,
            request_deserializer=protos_dot_p2p__pb2.QueryRequest.FromString,
            response_serializer=protos_dot_p2p__pb2.QueryResponse.SerializeToString,
        ),
        "GetVectorDigest": grpc.unary_unary_rpc_method_handler(
            servicer.GetVectorDigest,
            request_deserializer=protos_dot_p2p__pb2.Empty.FromString,
            response_serializer=protos_dot_p2p__pb2.DigestResponse.SerializeToString,
        ),
        "GetVectorsByIds": grpc.unary_unary_rpc_method_handler(
            servicer.GetVectorsByIds,
            request_deserializer=protos_dot_p2p__pb2.IdList.FromString,
            response_serializer=protos_dot_p2p__pb2.VectorList.SerializeToString,
        ),
        "GetPartitionCoordinatorId": grpc.unary_unary_rpc_method_handler(
            servicer.GetPartitionCoordinatorId,
            request_deserializer=protos_dot_p2p__pb2.Empty.FromString,
            response_serializer=protos_dot_p2p__pb2.IdResponse.SerializeToString,
        ),
        "RespondToPing": grpc.unary_unary_rpc_method_handler(
            servicer.RespondToPing,
            request_deserializer=protos_dot_p2p__pb2.Empty.FromString,
            response_serializer=protos_dot_p2p__pb2.BoolResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "p2p.P2PNode", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("p2p.P2PNode", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class P2PNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetId(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/p2p.P2PNode/GetId",
            protos_dot_p2p__pb2.Empty.SerializeToString,
            protos_dot_p2p__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Similarity(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/p2p.P2PNode/Similarity",
            protos_dot_p2p__pb2.VectorRequest.SerializeToString,
            protos_dot_p2p__pb2.SimilarityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Receive(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/p2p.P2PNode/Receive",
            protos_dot_p2p__pb2.ReceiveRequest.SerializeToString,
            protos_dot_p2p__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def IAmCoord(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/p2p.P2PNode/IAmCoord",
            protos_dot_p2p__pb2.Empty.SerializeToString,
            protos_dot_p2p__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetClusters(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/p2p.P2PNode/SetClusters",
            protos_dot_p2p__pb2.SetClustersRequest.SerializeToString,
            protos_dot_p2p__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SearchVectorsLocal(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/p2p.P2PNode/SearchVectorsLocal",
            protos_dot_p2p__pb2.SearchVectorsContext.SerializeToString,
            protos_dot_p2p__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Query(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/p2p.P2PNode/Query",
            protos_dot_p2p__pb2.QueryRequest.SerializeToString,
            protos_dot_p2p__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetVectorDigest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/p2p.P2PNode/GetVectorDigest",
            protos_dot_p2p__pb2.Empty.SerializeToString,
            protos_dot_p2p__pb2.DigestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetVectorsByIds(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/p2p.P2PNode/GetVectorsByIds",
            protos_dot_p2p__pb2.IdList.SerializeToString,
            protos_dot_p2p__pb2.VectorList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPartitionCoordinatorId(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/p2p.P2PNode/GetPartitionCoordinatorId",
            protos_dot_p2p__pb2.Empty.SerializeToString,
            protos_dot_p2p__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RespondToPing(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/p2p.P2PNode/RespondToPing",
            protos_dot_p2p__pb2.Empty.SerializeToString,
            protos_dot_p2p__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
