# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p2p.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "p2p.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tp2p.proto\x12\x03p2p"\x07\n\x05\x45mpty"K\n\x0bVectorPoint\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x0f\n\x07\x63luster\x18\x04 \x01(\t"T\n\x11\x41\x64\x64VectorsRequest\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12!\n\x07\x63ontent\x18\x02 \x03(\x0b\x32\x10.p2p.VectorPoint\x12\x0c\n\x04type\x18\x03 \x01(\t"T\n\x0cQueryRequest\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12&\n\rquery_vectors\x18\x02 \x03(\x0b\x32\x0f.p2p.VectorList\x12\x0c\n\x04topk\x18\x03 \x01(\x05"0\n\nVectorList\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\x12\n\ncluster_id\x18\x02 \x01(\t"K\n\x0bScoredPoint\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05score\x18\x02 \x01(\x02\x12!\n\x07payload\x18\x03 \x01(\x0b\x32\x10.p2p.VectorPoint"2\n\rQueryResponse\x12!\n\x07results\x18\x01 \x03(\x0b\x32\x10.p2p.ScoredPoint":\n\x08PeerInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08http_url\x18\x02 \x01(\t\x12\x10\n\x08grpc_url\x18\x03 \x01(\t"4\n\x14RegisterPeersRequest\x12\x1c\n\x05peers\x18\x01 \x03(\x0b\x32\r.p2p.PeerInfo"<\n\x12SetClustersRequest\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x16\n\x0e\x63ontent_pickle\x18\x02 \x01(\x0c\x32\xdf\x01\n\x07P2PNode\x12\x34\n\x0eReceiveVectors\x12\x16.p2p.AddVectorsRequest\x1a\n.p2p.Empty\x12\x32\n\tQueryPeer\x12\x11.p2p.QueryRequest\x1a\x12.p2p.QueryResponse\x12\x36\n\rRegisterPeers\x12\x19.p2p.RegisterPeersRequest\x1a\n.p2p.Empty\x12\x32\n\x0bSetClusters\x12\x17.p2p.SetClustersRequest\x1a\n.p2p.Emptyb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "p2p_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EMPTY"]._serialized_start = 18
    _globals["_EMPTY"]._serialized_end = 25
    _globals["_VECTORPOINT"]._serialized_start = 27
    _globals["_VECTORPOINT"]._serialized_end = 102
    _globals["_ADDVECTORSREQUEST"]._serialized_start = 104
    _globals["_ADDVECTORSREQUEST"]._serialized_end = 188
    _globals["_QUERYREQUEST"]._serialized_start = 190
    _globals["_QUERYREQUEST"]._serialized_end = 274
    _globals["_VECTORLIST"]._serialized_start = 276
    _globals["_VECTORLIST"]._serialized_end = 324
    _globals["_SCOREDPOINT"]._serialized_start = 326
    _globals["_SCOREDPOINT"]._serialized_end = 401
    _globals["_QUERYRESPONSE"]._serialized_start = 403
    _globals["_QUERYRESPONSE"]._serialized_end = 453
    _globals["_PEERINFO"]._serialized_start = 455
    _globals["_PEERINFO"]._serialized_end = 513
    _globals["_REGISTERPEERSREQUEST"]._serialized_start = 515
    _globals["_REGISTERPEERSREQUEST"]._serialized_end = 567
    _globals["_SETCLUSTERSREQUEST"]._serialized_start = 569
    _globals["_SETCLUSTERSREQUEST"]._serialized_end = 629
    _globals["_P2PNODE"]._serialized_start = 632
    _globals["_P2PNODE"]._serialized_end = 855
# @@protoc_insertion_point(module_scope)
